---
- hosts: all
  become: true
  become_user: parashu
  tasks:
   - name: install python pip
     apt:
       name: python3-pip
       state: present
   - name: install docker-py python module
     pip:
       name: docker-py      
       state: present
   - name: start the container
     docker_container:
       name: aadhyatechapp
       image: "parashu1151/aadhyatech:a3cf6cb"
       state: present
       published_ports:
               - 0.0.0.0:8080:8090     
